force-app/main/default/objects/Inhabitant__c/Inhabitant__c.object-meta.xml
<CustomObject>
    <label>Inhabitant</label>
    <nameField>
        <label>Inhabitant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inhabitants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>UPS - {000000}</displayFormat>
        <label>Mail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/fields/Delivered__c.field-meta.xml
<CustomField>
    <fullName>Delivered__c</fullName>
    <label>Delivered</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>At Carrier Facility</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Height_inches__c.field-meta.xml
<CustomField>
    <fullName>Height_inches__c</fullName>
    <label>Height (inches)</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Inhabitant__c.field-meta.xml
<CustomField>
    <fullName>Inhabitant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inhabitant</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Weight_Oz__c.field-meta.xml
<CustomField>
    <fullName>Weight_Oz__c</fullName>
    <label>Weight (Oz)</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Width_inches__c.field-meta.xml
<CustomField>
    <fullName>Width_inches__c</fullName>
    <label>Width (inches)</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ShippingPageController.cls
public inherited sharing class ShippingPageController {

    public ApexPages.StandardSetController ssc {get; set;}

    // delivery status that user wants to filter by 
    public String deliveryStatus {get; set;}

    // public String currentUserName{get{
    //     if(currentUserName == null){
    //         currentUserName = currentUser.Name;
    //     }
    //     return currentUserName;
    // }set;}

    public User currentUser {get{
        if(currentUser == null)
        {
            currentUser = [SELECT Id, Name FROM User WHERE Id=:userinfo.getuserId()];
        }
        return currentUser;
    } set;}

    // public static void shareMailRecord(Id mailToShare, Id userToShareWith){
    //     Mail__Share mShare = new Mail__Share();
    //     mShare.Id = mailToShare;
    //     mShare.UserOrGroupId = userToShareWith;
    //     mShare.AccessLevel = 'Read';
    //     mShare.RowCause = 'Manual';
    //     insert mShare;
    // }

    // what the list controller will sort by 
    private String sortedByVal = 'Name';

    // determines whether or not our list controller should filter
    private Boolean isFiltered = false;

    /* class constructor */
    public ShippingPageController() {
        this.deliveryStatus = 'View All';
        setSSC();
    }

    // @description mail getter
    public List<Mail__c> getMail(){
        return (List<Mail__c>)ssc.getRecords();
    }

// @description Sets our Standard List Controller, based off of whether or not it needs to be filtered 
public void setSSC(){

    String baseQuery = 'SELECT Inhabitant__r.Name, Name, Height_inches__c, Width_inches__c,' +  
                       'Weight_Oz__c, Route__c, Delivered__c FROM Mail__c WHERE Inhabitant__r.Name = \''
                       + currentuser.Name + '\' ';
    if(this.isFiltered){
        this.ssc = new ApexPages.StandardSetController(Database.query(
                baseQuery + ' AND Delivered__c = :deliveryStatus' + 
                ' ORDER BY '+ sortedByVal + ' ASC'
        ));
    } else {
        this.ssc = new ApexPages.StandardSetController(Database.query(
                baseQuery + 'ORDER BY '+ sortedByVal + ' ASC'
        ));
    }
}

    // @description Checks if our query needs to be filtered or not
    public void getStatus(){
        if(this.deliveryStatus == 'View All'){
            this.isFiltered = false;
        } else {
            this.isFiltered = true;
        }

        setSSC();
    }

    public void sortByName(){
        this.sortedByVal = 'Name';
        setSSC();
    }
    
    public void sortByHeight(){
        this.sortedByVal = 'Height_inches__c';
        setSSC();
    }

    public void sortByWidth(){
        this.sortedByVal = 'Width_inches__c';
        setSSC();
    }

    public void sortByWeight(){
        this.sortedByVal = 'Weight_Oz__c';
        setSSC();
    }

    public void sortByRoute(){
        this.sortedByVal = 'Route__c';
        setSSC();
    }

    public void sortByStatus(){
        this.sortedByVal = 'Delivered__c';
        setSSC();
    }

    public PageReference siteTemplateRedirect(){
        Pagereference newPage = Page.SiteTemplate;
        newPage.setRedirect(true);
        return newPage;
    }
}