force-app/main/default/objects/Inhabitant__c/Inhabitant__c.object-meta.xml
<CustomObject>
    <label>Inhabitant</label>
    <nameField>
        <label>Inhabitant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inhabitants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>UPS - {000000}</displayFormat>
        <label>Mail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Mail__c/fields/Delivered__c.field-meta.xml
<CustomField>
    <fullName>Delivered__c</fullName>
    <label>Delivered</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>At Carrier Facility</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Inhabitant__c.field-meta.xml
<CustomField>
    <fullName>Inhabitant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inhabitant</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mail__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Tracking_CC.cls
public class Tracking_CC {
	
    public List<Mail__c> mails {get;set;}
    public String searchText {get; set;}
    public Boolean searched{get; set;}
    
    
    public Tracking_CC(){
        searched = false;
        String nameStr = apexPages.currentPage().getParameters().get('searchText');
        if(null!=nameStr){
            searchText= nameStr;
        }
    }
    
    public PageReference search(){
        if(String.isNotBlank(searchText) && searchText.length() > 10){
            searched = true;
            String searchStr = searchText;
            mails = [SELECT ID, Name, Delivered__c, Inhabitant__r.name, Route__r.name FROM Mail__c WHERE Name Like: searchStr];
        } else {
            ApexPages.addMessage(
                new ApexPages.message(
                    ApexPages.severity.ERROR,
                    'Please enter tracking number in the form \'UPS - XXXXXX\''
                )
            );
        }
        return null;
    }

    public Pagereference siteTemplateRedirect(){
        Pagereference newPage = Page.SiteTemplate;
        newPage.setRedirect(true);
        return newPage;
    }
}